const Transaction = require("../models/transaction.model");
const Wallet = require("../models/wallet.model");
const Budget = require("../models/budget.model");

// Bütçe oluştur ve kaydet (createBudget)
// Bütçe bilgilerini getir (id ile) (getBudgetById)
// Bütçe bilgilerini getir (user id ile) (getBudgetsByUserId)
// Bütçe bilgilerini güncelle (updateBudget)
// Bütçeyi sil (deleteBudget)
// Bütçenin bakiyesini güncelle (updateBalance)
// Bütçenin bakiyesini kontrol et (checkBalance)
// Bütçenin bakiyesini güncelle (decreaseBalance)
// Bütçenin bakiyesini güncelle (increaseBalance)
// Bütçe silindiğinde bütçeye ait tüm işlemleri sil (deleteTransactions)
// Bütçe silindiğinde bütçeye ait tüm cüzdanları sil (deleteWallets)
// Bütçe silindiğinde bütçenin sahibine ait tüm cüzdanları sil (deleteWalletsByUserId)
// Bütçe silindiğinde bütçenin sahibine ait tüm işlemleri sil (deleteTransactionsByUserId)
// Bütçe silindiğinde bütçenin sahibine ait tüm işlemleri sil (deleteTransactionsByBudgetId)
// Bütçe silindiğinde bütçenin sahibine ait tüm işlemleri sil (deleteTransactionsByBudgetIdAndUserId)
// Bütçe renklerini getir (getColors)
// Bütçe renklerini güncelle (updateColor)
// Bütçenin sahibine ait tüm bütçeleri getir (getBudgetsByUserId)
// Bütçenin sahibine ait tüm bütçeleri sil (deleteBudgetsByUserId)
// Bütçenin işlemlerini getir (getTransactionsByBudgetId)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserId)
// Burdan sonrakiler filter işlemleri olacak tek apide yapılacak
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndWalletId)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletId)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDate)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRange)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndType)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategory)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategoryAndDescription)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategoryAndDescriptionAndAmount)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategoryAndDescriptionAndAmountAndCurrency)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategoryAndDescriptionAndAmountAndCurrencyAndTransactionDate)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategoryAndDescriptionAndAmountAndCurrencyAndTransactionDateAndCreatedAt)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategoryAndDescriptionAndAmountAndCurrencyAndTransactionDateAndCreatedAtAndUpdatedAt)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategoryAndDescriptionAndAmountAndCurrencyAndTransactionDateAndCreatedAtAndUpdatedAtAndDeletedAt)
// Bütçenin işlemlerini getir (getTransactionsByBudgetIdAndUserIdAndWalletIdAndDateRangeAndTypeAndCategoryAndDescriptionAndAmountAndCurrencyAndTransactionDateAndCreatedAtAndUpdatedAtAndDeletedAtAndIsDeleted)
// Bütçenin hatırlatıcılarını getir (getReminders)
// Bütçenin hatırlatıcılarını güncelle (updateReminder)
// Bütçenin hatırlatıcılarını sil (deleteReminder)
// Bütçenin hatırlatıcılarını sil (deleteRemindersByUserId)
// Bütçenin hatırlatıcılarını sil (deleteRemindersByBudgetId)
// Bütçenin hatırlatıcılarını sil (deleteRemindersByUserIdAndBudgetId)
// Bütçenin limitlerini getir (getLimits)
// Bütçenin limitlerini güncelle (updateLimit)
// Bütçenin limitlerini sil (deleteLimit)
// Bütçenin limitlerini sil (deleteLimitsByUserId)
// Bütçenin limitlerini sil (deleteLimitsByBudgetId)
// Bütçenin limitlerini sil (deleteLimitsByUserIdAndBudgetId)
// Bütçenin kategorilerini getir (getCategories)
// Bütçenin kategorilerini güncelle (updateCategory)
// Bütçenin kategorilerini sil (deleteCategory)
// Bütçenin kategorilerini sil (deleteCategoriesByUserId)
// Bütçenin kategorilerini sil (deleteCategoriesByBudgetId)
// Bütçenin kategorilerini sil (deleteCategoriesByUserIdAndBudgetId)
// Bütçenin kategorilerini sil (deleteCategoriesByUserIdAndBudgetIdAndCategoryId)
// Bütçenin kategorilerini sil (deleteCategoriesByUserIdAndBudgetIdAndCategoryIdAndCategoryName)